### PR TITLE
Fixed constraints in Main.storyboard. Call search functions.

### PR DESCRIPTION
**Pull request by Metaxa007**

### CODE REVIEW

**Comment by TomTasche** [comment]
works well, thank you! two improvements:
1. can't see the "next" button on iPhone 11 simulator (screenshot attached)
2. focus should go into search textfield automatically after it shows up

Screenshot 2020-06-15 at 21 42 39

**Comment by Metaxa007** [comment]
It is a bit tricky. After you typed a text you need to tap somewhere on the screen to make the searchBar out of focus. Then the button is visible again.

**Comment by TomTasche** [comment]
> It is a bit tricky. After you typed a text you need to tap somewhere on the screen to make the searchBar out of focus. Then the button is visible again.

Haha! 🤦 Why... Is that standard iOS behavior? If yes, ok and we can merge after you implemented #2

**Comment by Metaxa007** [comment]
Yes, unfortunately it is a standard behavior :(

**Comment by TomTasche** [comment]
perfect! thanks a lot! invoice please 🙂

**Comment by andiwand** [comment]
good job - looks great! 🎉

**Comment by Metaxa007** [comment]
@andiwand  thank you!

**Pull request merged**
